baseURL: "https://skerritt.blog"
languageCode: "en-us"
title: "Skerritt.blog"
theme: "hugo-PaperMod"
enableInlineShortcodes: true
enableRobotsTXT: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: tags
                  url: tags/
                  weight: 10
                - name: Popular
                  url: tags/popular/
                  weight: 15

permalinks:
  posts: :slug

custom_css:
  - "css/custom.css"

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Computer Science Blog"
    images:
            - /media/p2p.jpg

    author: Bee
    header:
            title: 'Skerritt.blog'
            imageUrl: '/media/p2p.jpg'
            subtitle: 'Learn Computer Science for free'
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    cover:
      responsiveImages: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "/media/p2p.jpg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: >
            I write about esoteric computer science topics that you'd love.
            - Writer, Hacker, Author, Programmer.
            
    socialIcons:
        - name: twitter
          url: "https://twitter.com/bee_sec_san"
        - name: linkedin
          url: "https://www.linkedin.com/in/brandonls"
        - name: github
          url: "https://github.com/bee-san"
        - name: buymeacoffee
          url: "https://buymeacoffee.com/beecodes"
        - name: rss 
          url: "https://skerritt.blog/index.xml"
        - name: email
          url: "mailto:brandon@skerritt.blog"
    cover:
            hidden: true # hide everywhere but not in structured data
            hiddenInList: true # hide on list pages and home
            hiddenInSingle: true # hide on single page

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
  goldmark:
    renderer:
      unsafe: true
