baseURL: "https://polymath.cloud"
languageCode: "en-us"
title: "Polymath.cloud"
theme: "bee-Papermod"
enableInlineShortcodes: true
enableRobotsTXT: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Computer Science Blog"
    author: Bee
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: >
            I write about esoteric computer science topics that you'd love.
            - Writer, Hacker, Author, Programmer.
    socialIcons:
        - name: twitter
          url: "#"
        - name: linkedin
          url: "https://twitter.com/bee_sec_san"
        - name: github
          url: "https://github.com/bee-san"
        - name: kofi
          url: "https://kofi.com/hacker"

taxonomies:
    category: categories
    tag: tags
    series: series
